# Generated by Django 5.0 on 2026-07-16 16:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_package_price'),
        ('students', '0005_prospectstatus_alter_prospect_prospect_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_quota', models.PositiveIntegerField(default=0, verbose_name='Total Kuota Dibeli')),
                ('used_quota', models.PositiveIntegerField(default=0, verbose_name='Kuota Terpakai')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Sisa Kuota')),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('EXPIRED', 'Kedaluwarsa'), ('DEPLETED', 'Habis')], default='ACTIVE', max_length=20)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.package')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='students.student')),
            ],
            options={
                'db_table': 'student_quotas',
            },
        ),
        migrations.CreateModel(
            name='QuotaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('ADD', 'Penambahan'), ('DEDUCT', 'Pengurangan'), ('ADJUST', 'Penyesuaian Manual')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, help_text='Nomor Invoice / Nomor Absen', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='quotas.studentquota')),
            ],
            options={
                'db_table': 'quota_transactions',
            },
        ),
    ]
