# Generated by Django 5.0 on 2026-07-14 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_employee_email_employee_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode Jabatan')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Jabatan')),
                ('category', models.CharField(choices=[('MANAGEMENT', 'Management'), ('ACADEMIC', 'Academic'), ('SALES', 'Sales & Marketing'), ('FINANCE', 'Finance & Admin'), ('SUPPORT', 'Support & Ops'), ('OTHER', 'Lainnya')], default='OTHER', max_length=20)),
                ('level', models.PositiveIntegerField(default=1, help_text='Tingkat jabatan (1 = tertinggi)')),
                ('is_teaching_position', models.BooleanField(default=False, help_text='Centang jika jabatan ini mengajar (Coach)')),
                ('requires_schedule', models.BooleanField(default=False)),
                ('requires_attendance', models.BooleanField(default=False)),
                ('requires_payroll', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True, verbose_name='Aktif')),
                ('parent_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.jobposition')),
            ],
            options={
                'db_table': 'job_positions',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.jobposition', verbose_name='Jabatan'),
        ),
    ]
