# Generated by Django 5.0 on 2026-07-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_employee_job_title_jobposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='is_finance_validator',
            field=models.BooleanField(default=False, help_text='Bisa memvalidasi pembayaran'),
        ),
    ]
