# Generated by Django 5.0 on 2026-07-14 21:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode Alasan')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Alasan')),
                ('applies_to', models.CharField(choices=[('STUDENT', 'Siswa'), ('COACH', 'Coach'), ('BOTH', 'Keduanya')], max_length=20, verbose_name='Berlaku Untuk')),
                ('classification', models.CharField(choices=[('EXCUSED', 'Excused (Diterima)'), ('UNEXCUSED', 'Unexcused (Ditolak)'), ('PENDING_VERIFICATION', 'Menunggu Verifikasi')], max_length=50, verbose_name='Klasifikasi')),
                ('is_makeup_eligible', models.CharField(choices=[('ELIGIBLE', 'Berhak Make-up'), ('NOT_ELIGIBLE', 'Tidak Berhak Make-up'), ('REQUIRES_APPROVAL', 'Memerlukan Persetujuan')], max_length=50, verbose_name='Kebijakan Make-up')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Nonaktif')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
            ],
            options={
                'verbose_name_plural': 'Absence Reasons',
                'db_table': 'absence_reasons',
            },
        ),
    ]
