FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy project files
COPY . .

EXPOSE 3000

# Start development server
CMD ["npm", "run", "dev"]
