# Generated by Django 5.0 on 2026-07-18 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('students', '0005_prospectstatus_alter_prospect_prospect_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.prospect'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student'),
        ),
    ]
