# Generated by Django 5.0 on 2026-07-14 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode Metode')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Metode (Contoh: Transfer BCA)')),
                ('processing_mode', models.CharField(choices=[('MANUAL', 'Manual'), ('SEMI_AUTO', 'Semi-Otomatis'), ('AUTO', 'Otomatis')], default='MANUAL', max_length=20, verbose_name='Mode Pemrosesan')),
                ('requires_reference', models.BooleanField(default=True, verbose_name='Wajib Nomor Referensi')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Nonaktif')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan Tambahan')),
            ],
            options={
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode Kategori')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('classification', models.CharField(choices=[('OPEX', 'Operasional/OPEX'), ('CAPEX', 'Investasi/CAPEX'), ('COGS', 'Harga Pokok/COGS'), ('ADMIN', 'Administrasi'), ('ACADEMIC', 'Akademik'), ('MARKETING', 'Pemasaran'), ('HR', 'HR / SDM'), ('INVENTORY', 'Inventaris'), ('OTHER', 'Lainnya')], max_length=20, verbose_name='Klasifikasi Biaya')),
                ('cost_nature', models.CharField(choices=[('FIXED', 'Tetap'), ('VARIABLE', 'Variabel'), ('PERIODIC', 'Berkala'), ('ONE_TIME', 'Satu Kali')], max_length=20, verbose_name='Sifat Biaya')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Nonaktif')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='finance.feecategory', verbose_name='Kategori Induk')),
            ],
            options={
                'verbose_name_plural': 'Fee Categories',
                'db_table': 'fee_categories',
            },
        ),
    ]
