from django.urls import path
from dompet import dompet_views
app_name='dompet'
urlpatterns = [
    path('',dompet_views.index,name="index"),
    path('index/',dompet_views.index,name="index"),
    path('index-2/',dompet_views.index_2,name="index-2"),
    path('index-3/',dompet_views.index_3,name="index-3"),
    path('index-4/',dompet_views.index_4,name="index-4"),
    path('index-5/',dompet_views.index_5,name="index-5"),
    path('index-6/',dompet_views.index_6,name="index-6"),
    path('index-7/',dompet_views.index_7,name="index-7"),
    path('index-8/',dompet_views.index_8,name="index-8"),
    path('my-wallet/',dompet_views.my_wallet,name="my-wallet"),
    path('page-invoices/',dompet_views.page_invoices,name="page-invoices"),
    path('cards-center/',dompet_views.cards_center,name="cards-center"),
    path('page-transaction/',dompet_views.page_transaction,name="page-transaction"),
    path('transaction-details/',dompet_views.transaction_details,name="transaction-details"),
    
    path('content/',dompet_views.content,name="content"),
    path('content-add/',dompet_views.content_add,name="content-add"),
    path('menu/',dompet_views.menu,name="menu"),
    path('email-template/',dompet_views.email_template,name="email-template"),
    path('add-email/',dompet_views.add_email,name="add-email"),
    path('blog/',dompet_views.blog,name="blog"),
    path('add-blog/',dompet_views.add_blog,name="add-blog"),
    path('blog-category/',dompet_views.blog_category,name="blog-category"),
    

    path('app-profile/',dompet_views.app_profile,name="app-profile"),
    path('post-details/',dompet_views.post_details,name="post-details"),
    path('email-compose/',dompet_views.email_compose,name="email-compose"),
    path('email-inbox/',dompet_views.email_inbox,name="email-inbox"),
    path('email-read/',dompet_views.email_read,name="email-read"),
    path('app-calender/',dompet_views.app_calender,name="app-calender"),
    path('ecom-product-grid/',dompet_views.ecom_product_grid,name="ecom-product-grid"),
    path('ecom-product-list/',dompet_views.ecom_product_list,name="ecom-product-list"),
    path('ecom-product-detail/',dompet_views.ecom_product_detail,name="ecom-product-detail"),
    path('ecom-product-order/',dompet_views.ecom_product_order,name="ecom-product-order"),
    path('ecom-checkout/',dompet_views.ecom_checkout,name="ecom-checkout"),
    path('ecom-invoice/',dompet_views.ecom_invoice,name="ecom-invoice"),
    path('ecom-customers/',dompet_views.ecom_customers,name="ecom-customers"),
    path('chart-flot/',dompet_views.chart_flot,name="chart-flot"),
    path('chart-morris/',dompet_views.chart_morris,name="chart-morris"),
    path('chart-chartjs/',dompet_views.chart_chartjs,name="chart-chartjs"),
    path('chart-chartist/',dompet_views.chart_chartist,name="chart-chartist"),
    path('chart-sparkline/',dompet_views.chart_sparkline,name="chart-sparkline"),
    path('chart-peity/',dompet_views.chart_peity,name="chart-peity"),

    path('ui-accordion/',dompet_views.ui_accordion,name="ui-accordion"),
    path('ui-alert/',dompet_views.ui_alert,name="ui-alert"),
    path('ui-badge/',dompet_views.ui_badge,name="ui-badge"),
    path('ui-button/',dompet_views.ui_button,name="ui-button"),
    path('ui-modal/',dompet_views.ui_modal,name="ui-modal"),
    path('ui-button-group/',dompet_views.ui_button_group,name="ui-button-group"),
    path('ui-list-group/',dompet_views.ui_list_group,name="ui-list-group"),
    path('ui-card/',dompet_views.ui_card,name="ui-card"),
    path('ui-carousel/',dompet_views.ui_carousel,name="ui-carousel"),
    path('ui-dropdown/',dompet_views.ui_dropdown,name="ui-dropdown"),
    path('ui-popover/',dompet_views.ui_popover,name="ui-popover"),
    path('ui-progressbar/',dompet_views.ui_progressbar,name="ui-progressbar"),
    path('ui-tab/',dompet_views.ui_tab,name="ui-tab"),
    path('ui-typography/',dompet_views.ui_typography,name="ui-typography"),
    path('ui-pagination/',dompet_views.ui_pagination,name="ui-pagination"),
    path('ui-grid/',dompet_views.ui_grid,name="ui-grid"),

    path('uc-select2/',dompet_views.uc_select2,name="uc-select2"),
    path('uc-nestable/',dompet_views.uc_nestable,name="uc-nestable"),
    path('uc-noui-slider/',dompet_views.uc_noui_slider,name="uc-noui-slider"),
    path('uc-sweetalert/',dompet_views.uc_sweetalert,name="uc-sweetalert"),
    path('uc-toastr/',dompet_views.uc_toastr,name="uc-toastr"),
    path('map-jqvmap/',dompet_views.map_jqvmap,name="map-jqvmap"),
    path('uc-lightgallery/',dompet_views.uc_lightgallery,name="uc-lightgallery"),
    path('uc-lightgallery/',dompet_views.uc_lightgallery,name="uc-lightgallery"),
    path('widget-card/',dompet_views.widget_card,name="widget-card"),
    path('widget-chart/',dompet_views.widget_chart,name="widget-chart"),
    path('widget-list/',dompet_views.widget_list,name="widget-list"),

    path('form-element/',dompet_views.form_element,name="form-element"),
    path('form-wizard/',dompet_views.form_wizard,name="form-wizard"),
    path('form-ckeditor/',dompet_views.form_ckeditor,name="form-ckeditor"),
    path('form-pickers/',dompet_views.form_pickers,name="form-pickers"),
    path('form-validation/',dompet_views.form_validation,name="form-validation"),

    path('table-bootstrap-basic/',dompet_views.table_bootstrap_basic,name="table-bootstrap-basic"),
    path('table-datatable-basic/',dompet_views.table_datatable_basic,name="table-datatable-basic"),

    path('page-login/',dompet_views.page_login,name="page-login"),
    path('page-register/',dompet_views.page_register,name="page-register"),
    path('page-forgot-password/',dompet_views.page_forgot_password,name="page-forgot-password"),
    path('page-lock-screen/',dompet_views.page_lock_screen,name="page-lock-screen"),
    path('page-error-400/',dompet_views.page_error_400,name="page-error-400"),
    path('page-error-403/',dompet_views.page_error_403,name="page-error-403"),
    path('page-error-404/',dompet_views.page_error_404,name="page-error-404"),
    path('page-error-500/',dompet_views.page_error_500,name="page-error-500"),
    path('page-error-503/',dompet_views.page_error_503,name="page-error-503"),
    path('empty-page/',dompet_views.empty_page,name="empty-page"),



]