# Generated by Django 5.0 on 2026-07-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_photo'),
        ('branches', '0005_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nama Permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nama Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='accounts.permission', verbose_name='Hak Akses'),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_branches',
            field=models.ManyToManyField(blank=True, to='branches.branch', verbose_name='Cabang Penugasan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Akun'),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, verbose_name='Gagal Login (Kali)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Akun Terkunci'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terkunci Sampai'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto Profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='accounts.role', verbose_name='Peran (Roles)'),
        ),
    ]
