# Generated by Django 5.0 on 2026-07-14 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode Kursus')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kursus')),
                ('category', models.CharField(choices=[('ACADEMIC', 'Akademik'), ('LANGUAGE', 'Bahasa'), ('TECHNOLOGY', 'Teknologi'), ('CREATIVITY', 'Kreativitas'), ('PRESCHOOL', 'Persiapan sekolah'), ('SELF_DEV', 'Pengembangan diri'), ('SPECIAL', 'Program khusus')], max_length=20, verbose_name='Kategori Kursus')),
                ('learning_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Kelompok'), ('BOTH', 'Individual dan kelompok')], max_length=20, verbose_name='Tipe Pembelajaran')),
                ('learning_mode', models.CharField(choices=[('OFFLINE', 'Tatap muka'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], max_length=20, verbose_name='Mode Pembelajaran')),
                ('default_duration', models.PositiveIntegerField(verbose_name='Durasi Default (menit)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Nonaktif')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, verbose_name='Kode Level')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Level')),
                ('order', models.PositiveIntegerField(verbose_name='Urutan')),
                ('use_course_duration', models.BooleanField(default=True, verbose_name='Gunakan Durasi Kursus')),
                ('custom_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durasi Khusus (menit)')),
                ('estimated_sessions', models.PositiveIntegerField(verbose_name='Estimasi Pertemuan')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Nonaktif')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='academics.course', verbose_name='Kursus')),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_levels', to='academics.level', verbose_name='Level Prasyarat')),
            ],
            options={
                'verbose_name_plural': 'Levels',
                'db_table': 'levels',
                'unique_together': {('course', 'code')},
            },
        ),
    ]
