# Generated by Django 5.0 on 2026-07-14 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicperiod_package_studyclass'),
        ('branches', '0005_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode Tahun Ajaran')),
                ('name', models.CharField(help_text='Misal: 2026/2027', max_length=100, verbose_name='Nama Tahun Ajaran')),
                ('start_year', models.PositiveIntegerField(verbose_name='Tahun Mulai')),
                ('end_year', models.PositiveIntegerField(verbose_name='Tahun Selesai')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Nonaktif')], default='ACTIVE', max_length=20)),
            ],
            options={
                'db_table': 'academic_years',
            },
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='is_global',
            field=models.BooleanField(default=True, verbose_name='Berlaku Semua Cabang'),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='learning_end',
            field=models.DateField(blank=True, null=True, verbose_name='KBM Selesai'),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='learning_start',
            field=models.DateField(blank=True, null=True, verbose_name='KBM Mulai'),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='period_type',
            field=models.CharField(choices=[('SEMESTER', 'Semester'), ('TERM', 'Term'), ('INTENSIVE', 'Intensif / Spesial')], default='SEMESTER', max_length=20),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='registration_end',
            field=models.DateField(blank=True, null=True, verbose_name='Pendaftaran Selesai'),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='registration_start',
            field=models.DateField(blank=True, null=True, verbose_name='Pendaftaran Mulai'),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('LOCKED', 'Locked'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai Periode'),
        ),
        migrations.AlterField(
            model_name='academicperiod',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai Periode'),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.academicyear'),
        ),
        migrations.CreateModel(
            name='BranchAcademicPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to='academics.academicperiod')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_periods', to='branches.branch')),
            ],
            options={
                'db_table': 'branch_academic_periods',
                'unique_together': {('branch', 'academic_period')},
            },
        ),
    ]
