# Generated by Django 5.0 on 2026-07-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='packages', to='academics.level', verbose_name='Level yang Berlaku'),
        ),
    ]
