# Generated by Django 5.0 on 2026-07-14 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('HEAD_OFFICE', 'Kantor Pusat'), ('BRANCH', 'Cabang'), ('SUB_BRANCH', 'Cabang Pembantu')], default='BRANCH', max_length=20, verbose_name='Jenis Cabang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(default='-', max_length=100, verbose_name='Kota/Kabupaten'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='deactivation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Nonaktif/Penutupan'),
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Cabang'),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branches/logos/', verbose_name='Logo Cabang'),
        ),
        migrations.AddField(
            model_name='branch',
            name='map_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lokasi Peta'),
        ),
        migrations.AddField(
            model_name='branch',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
        migrations.AddField(
            model_name='branch',
            name='operational_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai Operasional'),
        ),
        migrations.AddField(
            model_name='branch',
            name='parent_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_branches', to='branches.branch', verbose_name='Cabang Induk'),
        ),
        migrations.AddField(
            model_name='branch',
            name='person_in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='Penanggung Jawab'),
        ),
        migrations.AddField(
            model_name='branch',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kode Pos'),
        ),
        migrations.AddField(
            model_name='branch',
            name='province',
            field=models.CharField(default='-', max_length=100, verbose_name='Provinsi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nama Singkat'),
        ),
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Nonaktif'), ('CLOSED', 'Tutup')], default='ACTIVE', max_length=20, verbose_name='Status Cabang'),
        ),
        migrations.AddField(
            model_name='branch',
            name='status_effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Efektif Status'),
        ),
        migrations.AddField(
            model_name='branch',
            name='sub_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kelurahan/Desa'),
        ),
        migrations.AddField(
            model_name='branch',
            name='timezone',
            field=models.CharField(choices=[('Asia/Jakarta', 'WIB (Asia/Jakarta)'), ('Asia/Makassar', 'WITA (Asia/Makassar)'), ('Asia/Jayapura', 'WIT (Asia/Jayapura)')], default='Asia/Jakarta', max_length=50, verbose_name='Zona Waktu'),
        ),
        migrations.AddField(
            model_name='branch',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomor WhatsApp'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(default='-', verbose_name='Alamat Lengkap'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kode Cabang'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama Cabang'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone_number',
            field=models.CharField(default='-', max_length=50, verbose_name='Nomor Telepon'),
            preserve_default=False,
        ),
    ]
