# Generated by Django 5.0 on 2026-07-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_branch_type_branch_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='phone_number',
        ),
    ]
