# Generated by Django 5.0 on 2026-07-14 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_remove_branch_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, verbose_name='Kode Ruangan')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Ruangan')),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Ruang Kelas'), ('PRIVATE', 'Ruang Privat'), ('GROUP', 'Ruang Kelompok'), ('LABORATORY', 'Laboratorium'), ('MEETING', 'Ruang Rapat'), ('HALL', 'Aula/Multifungsi'), ('ADMINISTRATION', 'Ruang Administrasi'), ('OTHER', 'Lainnya')], max_length=20, verbose_name='Jenis Ruangan')),
                ('capacity_ideal', models.PositiveIntegerField(verbose_name='Kapasitas Ideal')),
                ('capacity_max', models.PositiveIntegerField(verbose_name='Kapasitas Maksimal')),
                ('facilities', models.JSONField(blank=True, default=list, null=True, verbose_name='Fasilitas Ruangan')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Nonaktif'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20, verbose_name='Status Ruangan')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='branches.branch', verbose_name='Cabang')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'unique_together': {('branch', 'code')},
            },
        ),
    ]
