# Generated by Django 5.0 on 2026-07-14 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nama Libur/Kegiatan')),
                ('holiday_type', models.CharField(choices=[('NATIONAL', 'Nasional'), ('JOINT_LEAVE', 'Cuti Bersama'), ('ACADEMIC_HOLIDAY', 'Libur Akademik'), ('BRANCH_HOLIDAY', 'Libur Cabang'), ('INTERNAL_EVENT', 'Kegiatan Internal'), ('MAINTENANCE', 'Maintenance'), ('SPECIAL_CONDITION', 'Keadaan Khusus')], max_length=50, verbose_name='Jenis Hari Libur')),
                ('date_start', models.DateField(verbose_name='Tanggal Mulai')),
                ('date_end', models.DateField(verbose_name='Tanggal Selesai')),
                ('operational_impact', models.CharField(choices=[('FULL_CLOSE', 'Cabang Tutup Total'), ('NO_CLASS_ADMIN_OPEN', 'Tidak Ada Kelas, Admin Tetap Buka'), ('LIMITED_OPERATIONS', 'Operasional Terbatas'), ('SPECIFIC_ACTIVITY_CLOSED', 'Hanya Kegiatan Tertentu Ditutup')], max_length=50, verbose_name='Dampak Operasional')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Nonaktif')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='branches.branch', verbose_name='Cabang')),
            ],
            options={
                'verbose_name_plural': 'Holidays',
                'db_table': 'holidays',
                'unique_together': {('branch', 'name', 'date_start')},
            },
        ),
    ]
