# Generated by Django 5.0 on 2026-07-14 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('branches', '0005_holiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('prospect_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Prospect')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nama Lengkap Calon Siswa')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nama Panggilan')),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10, verbose_name='Jenis Kelamin')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('nik_nisn', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIK/NISN')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='prospects/photos/', verbose_name='Foto Calon Siswa')),
                ('edu_status', models.CharField(choices=[('STUDENT', 'Pelajar'), ('WORKING', 'Bekerja'), ('NOT_WORKING', 'Tidak Bekerja')], max_length=20, verbose_name='Status Pendidikan')),
                ('school_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Sekolah')),
                ('edu_level', models.CharField(choices=[('PAUD_TK', 'PAUD/TK'), ('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('MAHASISWA', 'Mahasiswa'), ('UMUM', 'Umum')], max_length=20, verbose_name='Jenjang Sekolah')),
                ('current_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kelas Saat Ini')),
                ('school_entry_year', models.IntegerField(blank=True, null=True, verbose_name='Tahun Masuk Sekolah')),
                ('learning_goals', models.JSONField(default=list, verbose_name='Tujuan Mengikuti Kursus')),
                ('current_ability', models.TextField(blank=True, null=True, verbose_name='Kemampuan Saat Ini')),
                ('academic_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Akademik')),
                ('status', models.CharField(choices=[('NEW', 'Baru masuk'), ('CONTACTED', 'Sudah dihubungi'), ('INTERESTED', 'Berminat'), ('CONSULTATION', 'Sudah konsultasi'), ('TRIAL', 'Mengikuti trial'), ('OFFER_SENT', 'Penawaran diberikan'), ('WAITING_PAYMENT', 'Menunggu pembayaran'), ('ENROLLED', 'Sudah menjadi siswa'), ('NOT_INTERESTED', 'Tidak berminat'), ('LOST', 'Tidak berhasil dikonversi'), ('DUPLICATE', 'Data ganda')], default='NEW', max_length=20, verbose_name='Status Prospect')),
                ('last_followup_date', models.DateField(auto_now=True, verbose_name='Tanggal Follow-up Terakhir')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='Follow-up Berikutnya')),
                ('followup_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Follow-up')),
                ('lost_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alasan Tidak Lanjut')),
                ('distance_from_home', models.FloatField(blank=True, null=True, verbose_name='Jarak dari Rumah (km)')),
                ('branch_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alasan Memilih Cabang')),
                ('alt_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_alt_branches', to='branches.branch', verbose_name='Cabang Alternatif')),
                ('pic_followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_followups', to=settings.AUTH_USER_MODEL, verbose_name='PIC Follow-up')),
                ('target_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_target_branches', to='branches.branch', verbose_name='Cabang Tujuan')),
            ],
            options={
                'verbose_name_plural': 'Prospects',
                'db_table': 'prospects',
            },
        ),
        migrations.CreateModel(
            name='ProspectAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True, verbose_name='Alamat Lengkap')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kota')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kode Pos')),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='students.prospect')),
            ],
            options={
                'db_table': 'prospect_addresses',
            },
        ),
        migrations.CreateModel(
            name='ProspectInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('level_estimation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Level Perkiraan')),
                ('package_interest', models.CharField(blank=True, max_length=50, null=True, verbose_name='Paket Minat')),
                ('target_start_date', models.DateField(blank=True, null=True, verbose_name='Target Mulai')),
                ('interest_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Minat')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course', verbose_name='Kursus')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='students.prospect')),
            ],
            options={
                'db_table': 'prospect_interests',
            },
        ),
        migrations.CreateModel(
            name='ProspectParent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('relation', models.CharField(choices=[('AYAH', 'Ayah'), ('IBU', 'Ibu'), ('WALI', 'Wali'), ('SAUDARA', 'Saudara'), ('LAINNYA', 'Lainnya')], max_length=20, verbose_name='Hubungan dengan Siswa')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nama Orang Tua/Wali')),
                ('gender', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10, null=True, verbose_name='Jenis Kelamin')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Perusahaan')),
                ('whatsapp', models.CharField(max_length=50, verbose_name='Nomor WhatsApp')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomor Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('comm_preference', models.CharField(blank=True, choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('TELEPON', 'Telepon'), ('SMS', 'SMS')], max_length=20, null=True, verbose_name='Preferensi Komunikasi')),
                ('payer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Penanggung Jawab Pembayaran')),
                ('payer_relation', models.CharField(blank=True, choices=[('AYAH', 'Ayah'), ('IBU', 'Ibu'), ('WALI', 'Wali'), ('SAUDARA', 'Saudara'), ('LAINNYA', 'Lainnya')], max_length=20, null=True, verbose_name='Hubungan Payer')),
                ('payment_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Pembayaran')),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='students.prospect')),
            ],
            options={
                'db_table': 'prospect_parents',
            },
        ),
        migrations.CreateModel(
            name='ProspectSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('GOOGLE', 'Google Search'), ('WHATSAPP', 'WhatsApp'), ('REFERRAL', 'Referral Orang Tua'), ('SCHOOL', 'Sekolah'), ('EVENT', 'Event'), ('BROCHURE', 'Brosur'), ('TELEMARKETING', 'Telemarketing'), ('WALKIN', 'Walk-in')], max_length=50, verbose_name='Sumber Informasi')),
                ('source_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detail Sumber')),
                ('campaign', models.CharField(blank=True, max_length=255, null=True, verbose_name='Campaign')),
                ('referred_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referensi Oleh')),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='students.prospect')),
            ],
            options={
                'db_table': 'prospect_sources',
            },
        ),
        migrations.CreateModel(
            name='ProspectStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('old_status', models.CharField(choices=[('NEW', 'Baru masuk'), ('CONTACTED', 'Sudah dihubungi'), ('INTERESTED', 'Berminat'), ('CONSULTATION', 'Sudah konsultasi'), ('TRIAL', 'Mengikuti trial'), ('OFFER_SENT', 'Penawaran diberikan'), ('WAITING_PAYMENT', 'Menunggu pembayaran'), ('ENROLLED', 'Sudah menjadi siswa'), ('NOT_INTERESTED', 'Tidak berminat'), ('LOST', 'Tidak berhasil dikonversi'), ('DUPLICATE', 'Data ganda')], max_length=20)),
                ('new_status', models.CharField(choices=[('NEW', 'Baru masuk'), ('CONTACTED', 'Sudah dihubungi'), ('INTERESTED', 'Berminat'), ('CONSULTATION', 'Sudah konsultasi'), ('TRIAL', 'Mengikuti trial'), ('OFFER_SENT', 'Penawaran diberikan'), ('WAITING_PAYMENT', 'Menunggu pembayaran'), ('ENROLLED', 'Sudah menjadi siswa'), ('NOT_INTERESTED', 'Tidak berminat'), ('LOST', 'Tidak berhasil dikonversi'), ('DUPLICATE', 'Data ganda')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='students.prospect')),
            ],
            options={
                'db_table': 'prospect_status_history',
            },
        ),
    ]
