# Generated by Django 5.0 on 2026-07-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectaddress',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsi'),
        ),
    ]
