# Generated by Django 5.0 on 2026-07-14 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_prospectaddress_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('guardian_name', models.CharField(max_length=100, verbose_name='Nama Wali')),
                ('relationship', models.CharField(max_length=50, verbose_name='Hubungan dengan Siswa')),
                ('gender', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10, null=True, verbose_name='Jenis Kelamin')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan')),
                ('phone', models.CharField(max_length=50, verbose_name='Nomor HP/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat Wali')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Wali Utama')),
                ('status', models.CharField(default='Aktif', max_length=20, verbose_name='Status Wali')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan/Riwayat Perubahan')),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to='students.prospect')),
            ],
            options={
                'db_table': 'prospect_guardians',
            },
        ),
    ]
