# Generated by Django 5.0 on 2026-07-14 23:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_enrollment_enrollmenthistory_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
                ('allow_conversion', models.BooleanField(default=False)),
                ('requires_followup', models.BooleanField(default=False)),
                ('probability', models.PositiveIntegerField(default=0, help_text='Persentase keberhasilan 0-100')),
                ('color', models.CharField(default='primary', help_text='Warna label / class badge', max_length=20)),
                ('status', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'db_table': 'prospect_statuses',
                'ordering': ['sequence'],
            },
        ),
        migrations.AlterField(
            model_name='prospect',
            name='prospect_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='students.prospectstatus', verbose_name='Status Prospect'),
        ),
        migrations.AlterField(
            model_name='prospectstatushistory',
            name='new_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_histories', to='students.prospectstatus'),
        ),
        migrations.AlterField(
            model_name='prospectstatushistory',
            name='old_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_histories', to='students.prospectstatus'),
        ),
    ]
